# Generated by Django 6.0.5 on 2026-05-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeVeterinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_entree', models.CharField(choices=[('vaccin', 'Vaccination'), ('traitement', 'Traitement médical'), ('observation', 'Observation'), ('visite', 'Visite vétérinaire')], max_length=20)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('nb_poules_concernees', models.IntegerField(default=0)),
                ('cout_fcfa', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrees_veterinaires',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SuiviJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('nb_morts', models.IntegerField(default=0)),
                ('nb_vivantes', models.IntegerField(default=0)),
                ('nb_oeufs', models.IntegerField(default=0)),
                ('nourriture_kg', models.FloatField(default=0.0)),
                ('eau_litres', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'suivi_journalier',
                'ordering': ['-date'],
            },
        ),
    ]
