# Generated by Django 6.0.5 on 2026-05-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeManuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actionneur', models.CharField(max_length=20)),
                ('etat', models.BooleanField()),
            ],
            options={
                'db_table': 'commandes_manuelles',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EtatActionneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ventilateur', models.BooleanField(default=False)),
                ('lampe', models.BooleanField(default=False)),
                ('distributeur', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('auto', 'Automatique'), ('manuel', 'Manuel'), ('mqtt', 'MQTT')], default='auto', max_length=10)),
            ],
            options={
                'db_table': 'actionneurs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
