# Generated by Django 6.0.5 on 2026-05-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionneurs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatactionneur',
            name='sirene',
            field=models.BooleanField(default=False),
        ),
    ]
