# Generated by Django 6.0.5 on 2026-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionneurs', '0003_etatactionneur_sirene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etatactionneur',
            name='lampe',
        ),
        migrations.AddField(
            model_name='etatactionneur',
            name='ampoule_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etatactionneur',
            name='ampoule_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etatactionneur',
            name='ampoule_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etatactionneur',
            name='ampoule_4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etatactionneur',
            name='ampoule_5',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etatactionneur',
            name='ampoule_6',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etatactionneur',
            name='mode_eclairage',
            field=models.CharField(choices=[('auto', 'Automatique — LDR'), ('manuel', 'Manuel'), ('nuit', 'Mode nuit — toutes éteintes'), ('jour', 'Mode jour — toutes allumées')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandemanuelle',
            name='actionneur',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='etatactionneur',
            name='source',
            field=models.CharField(choices=[('auto', 'Automatique'), ('manuel', 'Manuel'), ('mqtt', 'MQTT'), ('ia', 'Intelligence artificielle')], default='auto', max_length=10),
        ),
    ]
