# Generated by Django 6.0.5 on 2026-05-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type_alerte', models.CharField(choices=[('CHALEUR', 'Chaleur excessive'), ('GAZ', 'Gaz dangereux'), ('HUMIDITE', 'Humidité anormale'), ('LUMINOSITE', 'Luminosité insuffisante')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('valeur', models.FloatField()),
                ('seuil', models.FloatField()),
                ('gravite', models.CharField(choices=[('critique', 'Critique'), ('avertissement', 'Avertissement')], max_length=15)),
                ('acquittee', models.BooleanField(default=False)),
                ('acquittee_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alertes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
