# Generated by Django 6.0.5 on 2026-05-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('CHALEUR', 'Chaleur excessive'), ('GAZ', 'Gaz dangereux'), ('HUMIDITE', 'Humidité anormale'), ('LUMINOSITE', 'Luminosité insuffisante'), ('EAU', 'Niveau eau faible'), ('INTRUSION', 'Intrusion détectée'), ('CO2', 'CO2 élevé'), ('NH3', 'Ammoniac élevé'), ('PREDICTION_CHALEUR', 'Prédiction chaleur IA'), ('IA_CHALEUR', 'Anomalie chaleur IA'), ('IA_HUMIDITE', 'Anomalie humidité IA'), ('IA_GAZ', 'Anomalie gaz IA')], max_length=20),
        ),
    ]
