# Generated by Django 6.0.5 on 2026-05-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_lot', models.CharField(choices=[('chair', 'Poulet de chair'), ('pondeuse', 'Pondeuse'), ('poussin', 'Poussin')], max_length=10)),
                ('nb_sujets', models.IntegerField()),
                ('date_arrivee', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('date_abattage_prevue', models.DateField(blank=True, null=True)),
                ('date_ponte_prevue', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lots',
                'ordering': ['-date_arrivee'],
            },
        ),
        migrations.CreateModel(
            name='VenteProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_vente', models.CharField(choices=[('oeufs', "Vente d'œufs"), ('poulets', 'Vente de poulets'), ('fumier', 'Vente de fumier'), ('autre', 'Autre')], max_length=10)),
                ('quantite', models.FloatField()),
                ('prix_unitaire_fcfa', models.FloatField()),
                ('montant_fcfa', models.FloatField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='lots_poulets.lot')),
            ],
            options={
                'db_table': 'ventes_production',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SuiviLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('semaine', models.IntegerField()),
                ('poids_moyen_g', models.FloatField(default=0)),
                ('nb_vivants', models.IntegerField(default=0)),
                ('nb_morts_semaine', models.IntegerField(default=0)),
                ('nourriture_kg', models.FloatField(default=0)),
                ('eau_litres', models.FloatField(default=0)),
                ('nb_oeufs', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='lots_poulets.lot')),
            ],
            options={
                'db_table': 'suivis_lots',
                'ordering': ['-date'],
                'unique_together': {('lot', 'semaine')},
            },
        ),
    ]
