# Generated by Django 6.0.5 on 2026-05-09 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots_poulets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('icone', models.CharField(default='cash', max_length=30)),
                ('couleur_hex', models.CharField(default='#6B7280', max_length=7)),
            ],
            options={
                'db_table': 'categories_depenses',
            },
        ),
        migrations.CreateModel(
            name='BudgetMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('budget_depenses_fcfa', models.FloatField(default=0)),
                ('budget_revenus_fcfa', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'budgets_mensuels',
                'unique_together': {('annee', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('montant_fcfa', models.FloatField()),
                ('notes', models.TextField(blank=True, default='')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.categoridepense')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='lots_poulets.lot')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'depenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Revenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_revenu', models.CharField(choices=[('oeufs', "Vente d'œufs"), ('poulets', 'Vente de poulets vivants'), ('viande', 'Vente de viande'), ('fumier', 'Vente de fumier'), ('autre', 'Autre')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.FloatField(default=1)),
                ('prix_unitaire_fcfa', models.FloatField()),
                ('montant_fcfa', models.FloatField()),
                ('notes', models.TextField(blank=True, default='')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenus', to='lots_poulets.lot')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'revenus',
                'ordering': ['-date'],
            },
        ),
    ]
