# Generated by Django 6.0.5 on 2026-05-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidite', models.FloatField()),
                ('gaz_ppm', models.IntegerField()),
                ('luminosite', models.IntegerField()),
            ],
            options={
                'db_table': 'mesures',
                'ordering': ['-timestamp'],
            },
        ),
    ]
