# Generated by Django 6.0.5 on 2026-05-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='nb_poules',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesure',
            name='niveau_eau',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='mesure',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
