# Generated by Django 6.0.5 on 2026-05-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0002_mesure_nb_poules_mesure_niveau_eau_mesure_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoIntrusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_base64', models.TextField(blank=True, default='')),
                ('description', models.CharField(default='Intrusion détectée', max_length=255)),
                ('zone', models.CharField(default='Zone principale', max_length=50)),
                ('acquittee', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'photos_intrusion',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='mesure',
            name='co2_ppm',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='mesure',
            name='nb_ampoules_allumees',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='mesure',
            name='nh3_ppm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mesure',
            name='photo_intrusion_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
